# Spring
spring:
  application:
    name: kafka-demo
  profiles:
    active: local

  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  # JSON Pretty Print
  jackson:
    serialization:
      indent-output: true
    deserialization:
      accept-empty-array-as-null-object: true

  kafka:
    group-id: kafka-demo
    enabled: true
    topic:
      consumer:
        customer: customer
      producer:
        delivery: delivery
    bootstrap-servers:
      localhost:9092

# Server
server:
  port: 8080
  compression.enabled: true
  compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    use-relative-redirects: true
